# Generated by Django 4.2 on 2026-03-20 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_auxiliar', models.CharField(max_length=8)),
                ('tipo_costo', models.CharField(choices=[('INGRESO', 'INGRESO'), ('GASTO', 'GASTO'), ('COSTO_VENTA', 'COSTO VENTA'), ('INSUMOS', 'INSUMOS'), ('MANO_OBRA', 'MANO OBRA'), ('CIF', 'CIF')], max_length=20)),
                ('detalle_costo', models.CharField(choices=[('INGRESO', 'INGRESO'), ('GASTO', 'GASTO'), ('COSTO_VENTA', 'COSTO DE VENTA'), ('INSUMOS', 'INSUMOS'), ('MANO_OBRA', 'MANO DE OBRA'), ('CIF_OTROS_CIF', 'CIF OTROS CIF'), ('CIF_HONORARIOS', 'CIF OTROS HONORARIOS'), ('CIF_ARRENDAMIENTO', 'CIF ARRENDAMIENTO'), ('CIF_ALQUILER_EQUIPO', 'CIF ALQUILER EQUIPO MEDICO'), ('CIF_ARREN_OTROS', 'CIF ARREN. OTROS ACTIVOS'), ('CIF_SERV_PUBLICOS', 'CIF SERVICIOS PUBLICOS'), ('CIF_TRANSPORTE', 'CIF TRANSPORTE Y ALOJAMIENTO'), ('CIF_OTROS_SERV', 'CIF OTROS SERVICIOS'), ('CIF_SALA', 'CIF DERECHOS DE SALA'), ('CIF_ANESTESIA', 'CIF ANESTESIOLOGIA'), ('CIF_PATOLOGIA', 'CIF PATOLOGIA'), ('OXIGENO', 'OXIGENO'), ('CILINDRO_MEZCLA', 'CILINDRO MEZCLA DE DIFUSIÓN'), ('CIF_MED_INSUMOS', 'CIF MEDICAMENTOS E INSUMOS (PROCEDIMIENTOS)'), ('CIF_MANTENIMIENTO', 'CIF MANTENIMIENTO'), ('CIF_DEPRECIACION', 'CIF DEPRECIACION'), ('CIF_COPAGOS', 'CIF COPAGOS ASUMIDOS'), ('CIF_ASEO_CAFE', 'OTROS CIF ELEMENTOS DE ASEO Y CAFETERIA'), ('CIF_PAPELERIA', 'OTROS CIF UTILES, PAPELERIA Y FOTOCOPIAS')], max_length=50)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
