# Generated by Django 4.2 on 2026-03-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMovimientosContables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('auxiliar', models.CharField(max_length=8)),
                ('desc_auxiliar', models.CharField(max_length=100)),
                ('c_o_mvto', models.CharField(max_length=100, verbose_name='C.O. Movimiento')),
                ('desc_c_o_mvto', models.CharField(max_length=100, verbose_name='Descripción C.O.')),
                ('unidad_negocio_codigo', models.CharField(max_length=4)),
                ('desc_unidad_negocio', models.CharField(max_length=100)),
                ('docto_proveedor', models.CharField(max_length=100)),
                ('tercero_mvto', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tipo_doc_contable', models.CharField(max_length=100)),
                ('grupo_contable', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento Contable',
                'verbose_name_plural': 'Detalles de Movimientos Contables',
                'ordering': ['-fecha', 'auxiliar'],
            },
        ),
        migrations.AlterField(
            model_name='tipocosto',
            name='detalle_costo',
            field=models.CharField(choices=[('INGRESO', 'INGRESO'), ('GASTO', 'GASTO'), ('COSTO_VENTA', 'COSTO DE VENTA'), ('INSUMOS', 'INSUMOS'), ('MANO_OBRA', 'MANO DE OBRA'), ('CIF_OTROS_CIF', 'CIF OTROS CIF'), ('CIF_HONORARIOS', 'CIF OTROS HONORARIOS'), ('CIF_ARRENDAMIENTO', 'CIF ARRENDAMIENTO'), ('CIF_ALQUILER_EQUIPO', 'CIF ALQUILER EQUIPO MEDICO'), ('CIF_ARREN_OTROS', 'CIF ARREN. OTROS ACTIVOS'), ('CIF_SERV_PUBLICOS', 'CIF SERVICIOS PUBLICOS'), ('CIF_TRANSPORTE', 'CIF TRANSPORTE Y ALOJAMIENTO'), ('CIF_OTROS_SERV', 'CIF OTROS SERVICIOS'), ('CIF_SALA', 'CIF DERECHOS DE SALA'), ('CIF_ANESTESIA', 'CIF ANESTESIOLOGIA'), ('CIF_PATOLOGIA', 'CIF PATOLOGIA'), ('OXIGENO', 'OXIGENO'), ('CILINDRO_MEZCLA', 'CILINDRO MEZCLA DE DIFUSIÓN'), ('CIF_MED_INSUMOS', 'CIF MEDICAMENTOS E INSUMOS (PROCEDIMIENTOS)'), ('CIF_MANTENIMIENTO', 'CIF MANTENIMIENTO'), ('CIF_DEPRECIACION', 'CIF DEPRECIACION'), ('CIF_COPAGOS', 'CIF COPAGOS ASUMIDOS'), ('CIF_ASEO_CAFE', 'OTROS CIF ELEMENTOS DE ASEO Y CAFETERIA'), ('CIF_PAPELERIA', 'OTROS CIF UTILES, PAPELERIA Y FOTOCOPIAS'), ('CIF_TRANSPORTE_EQUIPO_MEDICO', 'CIF TRANSPORTE EQUIPO MÉDICO')], max_length=50),
        ),
    ]
