# Generated by Django 4.2 on 2026-04-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingestion', '0003_detallemovimientoscontables_mapeo_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocosto',
            name='detalle_costo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipocosto',
            name='tipo_costo',
            field=models.CharField(max_length=20),
        ),
    ]
